name: 📖 Documentation Update
description: Suggest how we can improve our documentation
title: '[]: '
labels: '[documentation]'
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this documenation update report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: >-
        Please search to see if an issue already exists for the documenation
        update you want to propose.
      options:
        - label: I have searched the existing issues.
          required: true
  - type: textarea
    attributes:
      label: What does the current documentation state?
      description: >-
        Copy and paste the text currently in the documentation. If you want
        improve graphs or photos, please provide a screenshot of the original.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Where is this stated?
      description: >-
        Provide additional information about the location where you have copied
        the above statement from.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why do you want to improve the statement?
      description: >-
        Please explain why the statement needs to be updated. This can be
        because it is confusing, incorrect, spelling/grammatical errors, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed statement
      description: >-
        Please propose how you would rewrite the statement. If you have a
        precise proposal, please make the changes and open a pull-request.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: >-
        Anything other than the above mentioned to support your documentation
        update report here. Links? References? Screenshots? Anything that will
        give us more context about your report!
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: >-
        By submitting this issue, you agree to follow our [Code of
        Conduct](https://github.com/moja-global/About_moja_global/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
