name: Science Contribution and Review
description: Suggest how the science behind the code can be improved
title: "Science Contribution and Review: "
labels: [science-review]

body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to file a Science Contribution and Review report.
  - type: textarea
    attributes:
      label: Please describe the problem.
      description: 'A clear and concise description of what the problem is.'
  - type: textarea
    attributes:
      label: Describe the correct or improved scientific approach.
      description: 'A clear and concise description of what you want to happen.'
  - type: textarea
    attributes:
      label: Describe alternatives that could be considered
      description: 'A clear and concise description of any alternative solutions that would be scientifically correct.'
  - type: textarea
    attributes:
      label: Additional context.
      description: 'Add any other context or screenshots about the feature request here.'
