name: 🔎 Science Contribution and Review
description: Suggest how the science behind the code can be improved.
title: '[]: '
labels: '[feature]'
body:
  - type: markdown
    attributes:
      value: >-
        Thanks for taking the time to fill out this Science Contribution and
        Review report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: >-
        Please search to see if an issue already exists for the feature you want
        to propose.
      options:
        - label: I have searched the existing issues.
          required: true
  - type: textarea
    attributes:
      label: Please describe the problem.
      description: A clear and concise description of what the problem is.
  - type: textarea
    attributes:
      label: Describe the correct or improved scientific approach.
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives that could be considered
      description: >-
        A clear and concise description of any alternative solutions that would
        be scientifically correct.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: >-
        Anything other than the above mentioned to support your science
        contribution and review report here. Links? References? Screenshots?
        Anything that will give us more context about your suggestion!
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: >-
        By submitting this issue, you agree to follow our [Code of
        Conduct](https://github.com/moja-global/About_moja_global/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
