name: User Feedback
description: Describe how we can improve your experience
title: "User Feedback: "
labels: [user-feedback]

body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to file a User Feedback report.
  - type: textarea
    attributes:
      label: Describe what you are trying to do and why it is not optimal.
      description: 'A clear and concise description of what the problem is. Ex. When I reach this point, I cannot [...]'
  - type: textarea
    attributes:
      label: Describe the solution you'd like.
      description: 'A clear and concise description of what you want to happen.'
  - type: textarea
    attributes:
      label: Describe alternatives you've considered.
      description: 'A clear and concise description of any alternative solutions or features you have considered.'
  - type: textarea
    attributes:
      label: Additional context.
      description: 'Add any other context or screenshots about the feature request here.'
