name: Build Size

on:
  pull_request:
    branches:
      - main

jobs:
  compressed_size:
    name: Compressed Size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run compressed Size action
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          pattern: '{
                    ./build/main*js,
                    ./build/styles*css,
                    ./build/index.html,
                    ./build/blog/index.html*,
                    ./build/docs/index.html
                    }'
          strip-hash: '\.([^;]\w{7})\.'
          minimum-change-threshold: 100
          cwd: ./website
