name: Build Performance

on:
  pull_request:
    branches:
      - main

jobs:
  build-time:
    name: Build Time Performance
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Installation
        run: cd website && yarn install

      - name: Build (cold cache)
        run: cd website && yarn build
        timeout-minutes: 5

      - name: Build (warm cache)
        run: cd website && yarn build
        timeout-minutes: 1
