name: Trigger Contributors list 

on:
  schedule:
    # At 00:00 UTC on every Monday
    - cron: '0 0 * * 0'

jobs:
  build:
    name: Trigger Contributors list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Run Contributors script
        run: |
          cd website
          npm install request --save
          node ./scripts/fetchContributors.js
          rm package-lock.json
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: 'website'
          default_author: github_actor
          message: 'Update contributors'
          signoff: true